-- Create user_roadmaps table to store generated AI roadmaps for users
CREATE TABLE public.user_roadmaps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    
    -- Stores the specific user inputs that generated this roadmap
    user_input JSONB NOT NULL,     
    
    -- Stores the hierarchical Phase -> Topic -> Item tree generated by AI
    structure JSONB NOT NULL,      
    
    is_active BOOLEAN NOT NULL DEFAULT false,  -- If this is the currently active/selected roadmap
    is_deleted BOOLEAN NOT NULL DEFAULT false, -- Soft delete flag
    metadata JSONB DEFAULT '{}'::jsonb,        -- Extensible metadata for the roadmap
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexing for performance
CREATE INDEX idx_user_roadmaps_user_id ON public.user_roadmaps(user_id) WHERE is_deleted = false;

-- Ensure at most one active roadmap per user (excluding deleted ones)
CREATE UNIQUE INDEX idx_user_roadmaps_active ON public.user_roadmaps(user_id) WHERE (is_active = true AND is_deleted = false);

-- Enable Row-Level Security (RLS) on this table
ALTER TABLE public.user_roadmaps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own roadmaps" ON public.user_roadmaps
    FOR SELECT TO authenticated USING (auth.uid() = user_id AND is_deleted = false);

CREATE POLICY "Users can insert their own roadmaps" ON public.user_roadmaps
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own roadmaps" ON public.user_roadmaps
    FOR UPDATE TO authenticated USING (auth.uid() = user_id);
